# Generated by Django 5.2.7 on 2026-10-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_existing_accounts_become_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
